# Database Connection
spring.application.name=DronaOS
spring.datasource.url=jdbc:postgresql://localhost:5432/drona_os_dev
spring.datasource.username=drona_os_admin
spring.datasource.password=rootpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration (Turn off auto-table generation)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway Configuration (Critical for Multi-Tenancy)
# This forces Flyway to ONLY run the scripts in the 'public' folder when the app starts
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/public
spring.flyway.default-schema=public